-- CreateTable
CREATE TABLE "Link" (
    "assignedEnding" STRING NOT NULL,
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "url" STRING NOT NULL,
    "created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated" TIMESTAMP(3) NOT NULL,
    "email" STRING NOT NULL,
    "name" STRING NOT NULL,
    "description" STRING,
    "totalClicks" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "Link_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Link_assignedEnding_key" ON "Link"("assignedEnding");
